# Generated by Django 4.0 on 2021-12-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=50, verbose_name='Habilidad')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['id'], 'verbose_name': 'Trabajadore'},
        ),
        migrations.AlterUniqueTogether(
            name='persona',
            unique_together={('first_name', 'last_name')},
        ),
        migrations.AddField(
            model_name='persona',
            name='habilidades',
            field=models.ManyToManyField(to='persona.Habilidades'),
        ),
    ]
