# Generated by Django 4.0 on 2021-12-17 21:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_persona_hoja_vida'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='hoja_vida',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
