# Generated by Django 4.0 on 2021-12-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_persona_full_name_alter_persona_hoja_vida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='job',
            field=models.CharField(choices=[('0', 'CONTADOR'), ('1', 'ADMINISTRADOR'), ('2', 'ECONOMISTA'), ('3', 'DESARROLLADOR'), ('4', 'OTRO')], max_length=1, verbose_name='Trabajo'),
        ),
    ]
